# -*- coding: utf-8 -*-
"""Assignment 2- Question1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PIvxqucSvz2_7IqJMVI3znOJjUC148xk
"""

from google.colab import drive
drive.mount('/content/gdrive')
path_to_csv = '/content/gdrive/My Drive/data.csv'
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
# Read the provided CSV file ‘data.csv’
dataset = pd.read_csv(path_to_csv)
dataset

# Show the basic statistical description about the data.
dataset.describe()

# Check for null values
null_values = dataset.isnull().values.any()
print('If there any null values: ',null_values)

# Replace null values with mean
mean_values = dataset.mean()
dataset = dataset.fillna(mean_values)
values = dataset.isnull().values.any()
print('Are there any null values after using fillna:',values)

# Select at least two columns and aggregate the data using: min, max, count, mean.
agg = dataset.groupby('Duration').agg({'Pulse':['mean','min','max','count']})
agg

# Filter the dataframe to select the rows with calories values between 500 and 1000
dataset[(dataset['Calories']>=500) & (dataset['Calories']<=1000)]

# Filter the dataframe to select the rows with calories values > 500 and pulse < 100
dataset[(dataset['Calories']>500) & (dataset['Pulse']<100)]

# Create a new “df_modified” dataframe that contains all the columns from df except for “Maxpulse”
modified = dataset[['Duration', 'Pulse', 'Calories']]
modified

# Delete the “Maxpulse” column from the main  dataframe
dataset = dataset.drop('Maxpulse', axis=1)
dataset

# Convert the datatype of Calories column to int datatype
dataset['Calories'] = dataset['Calories'].astype('int64')
dataset.dtypes

#Using pandas create a scatter plot for the two columns (Duration and Calories).
import matplotlib.pyplot as plt
dataset.plot.scatter(x='Duration', y='Calories')
# Set the plot title and labels
plt.title('Scatter Plot: Duration vs Calories')
plt.xlabel('Duration')
plt.ylabel('Calories')
# Display the plot
plt.show()